project:
  type: website
  resources:
    - "**/*.pdf"

website:
  title: "Joseph Casey"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: articles/index.qmd
        text: Articles
      - href: projects/index.qmd
        text: Projects
      - href: research/index.qmd
        text: Research
      - href: archive/index.qmd
        text: Archive
      # - href: about/index.qmd
      #   text: About
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



