project:
  type: website

website:
  title: "Math and Coding Projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - mathematics.qmd
      - research.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



