## Natural Language Processing

This section contains selected coursework from a course in natural language processing. The assignments covered classical NLP materials through advanced transformer based LLMs.

The coursework includes work with tokenization and byte-pair encoding, language modeling, text classification, named entity recognition, and biomedical NLP. Later assignments involved transformer models and pretrained language models such as BERT and GPT..

I also completed a project involving distributed machine learning for NLP, using BERT-based representations and comparing approaches for training models across distributed datasets.

The jupyter code files are on my Github just for archiving, containing some useful reminders and manual implementations of nlp tasks.

[View the NLP coursework on GitHub →](https://github.com/josephcasey922/coursework-archive)


## Convex Optimization

These are my personal notes based on Nesterov's *Introductory Lectures
on Convex Optimization*. The notes were designed for my personal use in finding useful optimization results quickly using latex. In the book, I required a deeper explanation for the theorems and proofs, motivating my construction of these notes to add explanations
for the theorems and certain proof steps.

> **Note:** These notes are currently a work in progress for Chapters 1 and Chapters 2 and may contain many
> errors. I plan to revise them and add substantially more exposition over time.

[Download the current notes (PDF)](files/convex-optimization-notes.pdf)
